// Dailymotion Player Embed v-0.0.3663-rc1
// This file is generated dynamically, do not host it yourself
// Statically hosting or caching this file will break your integration
'use strict';var _dmpesplayer=function(){function da(){return(new URL(window.location.href)).searchParams.get("dmLogger")||""}function ea(a,b){if(Ea&&console[b]){for(var c=arguments.length,d=Array(2<c?c-2:0),f=2;f<c;f++)d[f-2]=arguments[f];c=[`%cPES%c${Fa[a]||"UNKNOWN TOPIC"}`,"border-radius: 0.125rem; padding: 0.0625rem 0.1875rem; margin: 0 0.0625rem; color: white;; background: purple","border-radius: 0.125rem; padding: 0.0625rem 0.1875rem; margin: 0 0.0625rem; color: white;; background: #ae27ae",
...d];console[b](...c)}}function Ga(){let a=null;if(A())return g.log("cookies","Skipping 3rd party cookie detection on dailymotion.com"),Promise.resolve();let b=new Promise(d=>{a=setTimeout(()=>{g.log("cookies","Received 3rd party cookie detection timeout");return d()},2E3)}),c=new Promise(d=>{if(A())return g.log("Skipping 3rd party cookie detection on dailymotion.com"),d();const f=document.createElement("script");f.src=`${L()?"https://geo2.dailymotion.com":"https://geo.dailymotion.com"}/cookie.js`;
f.onload=()=>{g.log("cookies","3rd party cookie detection script loaded");clearTimeout(a);return d()};f.onerror=()=>{g.log("cookies","3rd party cookie detection script error");clearTimeout(a);return d()};document.head.appendChild(f)});return Promise.race([c,b])}let fa=a=>new Promise((b,c)=>{const d=a.getAttribute("load-status");if("loaded"===d)return b();if("error"===d)return c();a.addEventListener("load",()=>{a.setAttribute("load-status","loaded");b()});a.addEventListener("error",()=>{a.setAttribute("load-status",
"error");c()})}),B={"udger":{"browserOsFamily":"Linux","browserOsName":"Linux","browserUaFamily":"Firefox","browserUaName":"Firefox 130.0","browserUaVersion":130,"deviceType":"desktop"},"geoip":{"visitorAsNumber":"AS17072","visitorCity":"Guadalajara","visitorContinent":"NA","visitorCountry":"MX","visitorRegion":"JAL"},"playerEnv":"prod","playerGatekeepers":["PV5_ADSENSE_DISPLAY_PREROLL","PV5_AD_BUFFET","PV5_AD_COOKIE_SYNC","PV5_AUDIO_ADS_POC","PV5_COOKIE_SYNC_AB_TEST","PV5_ENABLE_IMA_OMSDK","PV5_IAS_INAPP","PV5_IGNORE_EARLY_LOAD_MIDROLL","PV5_IMA_NATIVE_POC","PV5_IMA_OVERLAY","PV5_LIVE_MIDROLL_DISABLED","PV5_MULTI_FALLBACK","PV5_OMSDK","PV5_OMSDK_NATIVE","PV5_PROXY_LOAD_POSTROLL","PV5_SAVE_VAST_RECORD","PV5_TEMP_IMA_PAGEURL","PV5_TEMP_IMA_PAGEURL_OFFSITE","PV5_SIMID","PV5_MIDROLL_RETAKE_ONSITE","PV5_MIDROLL_RETAKE_OFFSITE","PV5_V2V_ONSITE_QUERY","PV5_ADS_ON_REPLAY_ONSITE","PV5_ADS_ON_REPLAY_OFFSITE","PV5_IMA_COMPANION_AD","PV5_INFOPACK_ENABLED_ONSITE","PV5_USE_GEO2_IFRAME_APAC"],"trafficSegment":116039,"v1st":"1089ec63-19df-4dc4-88a2-6f298d772148","player":{"id":"xnri6","ownerId":"x1mbetv","status":"ok","aspectRatio":"16:9","autoskipAfter":30,"autostart":"off","color":"","contextualContentSource":"channel","enableAdsAutopauseInactiveTab":false,"enableAdsControls":true,"enableAutomaticRecommendations":false,"enableAutonext":false,"enableAutoskip":false,"enableChannelLink":true,"enableClickToUnmute":true,"enableContextualContent":false,"enableCustomRecommendations":false,"enableDmLogo":true,"enableGooglePolicyUi":false,"enableInfo":false,"enableLiveOffairScreen":true,"enablePaidPartnershipLabel":false,"enablePlaybackControls":true,"enableReceiveUrlLocation":true,"enableSharing":true,"enableSharingUrlLocation":false,"enableStartPipExpanded":false,"enableStartscreenDmLink":true,"enableSubtitles":true,"enableTapToUnmute":true,"enableTitlesInVideoCards":true,"enableVideoTitleLink":true,"enableWaitForCustomConfig":true,"hasAds":true,"hasReachedPlaybackLimits":false,"hasSsai":false,"pip":"off","recommendationsOptimisation":"monetization","watermarkImageType":"none","watermarkImageUrl":"","watermarkLinkType":"none","watermarkLinkUrl":""}},ha=[{key:"id",isPublic:!0,isTrackable:!0},{key:"ownerId",isPublic:!1,isTrackable:!1},{key:"status",isPublic:!1,isTrackable:!1},{key:"aspectRatio",isPublic:!0,isTrackable:!0},{key:"autoskipAfter",isPublic:!0,isTrackable:!0},{key:"autostart",isPublic:!0,isTrackable:!0},{key:"color",isPublic:!0,isTrackable:!0},{key:"contextualContentSource",isPublic:!0,isTrackable:!0},{key:"enableAdsAutopauseInactiveTab",isPublic:!1,isTrackable:!0},{key:"enableAdsControls",isPublic:!0,
isTrackable:!0},{key:"enableAutomaticRecommendations",isPublic:!0,isTrackable:!0},{key:"enableAutonext",isPublic:!0,isTrackable:!0},{key:"enableAutoskip",isPublic:!0,isTrackable:!0},{key:"enableChannelLink",isPublic:!0,isTrackable:!0},{key:"enableClickToUnmute",isPublic:!0,isTrackable:!0},{key:"enableContextualContent",isPublic:!0,isTrackable:!0},{key:"enableCustomRecommendations",isPublic:!0,isTrackable:!0},{key:"enableDmLogo",isPublic:!0,isTrackable:!0},{key:"enableGooglePolicyUi",isPublic:!0,isTrackable:!0},
{key:"enableInfo",isPublic:!0,isTrackable:!0},{key:"enableLiveOffairScreen",isPublic:!0,isTrackable:!0},{key:"enablePaidPartnershipLabel",isPublic:!0,isTrackable:!0},{key:"enablePlaybackControls",isPublic:!0,isTrackable:!0},{key:"enableReceiveUrlLocation",isPublic:!0,isTrackable:!0},{key:"enableSharing",isPublic:!0,isTrackable:!0},{key:"enableSharingUrlLocation",isPublic:!0,isTrackable:!0},{key:"enableStartPipExpanded",isPublic:!0,isTrackable:!0},{key:"enableStartscreenDmLink",isPublic:!0,isTrackable:!0},
{key:"enableSubtitles",isPublic:!0,isTrackable:!0},{key:"enableTapToUnmute",isPublic:!0,isTrackable:!0},{key:"enableTitlesInVideoCards",isPublic:!0,isTrackable:!0},{key:"enableVideoTitleLink",isPublic:!0,isTrackable:!0},{key:"enableWaitForCustomConfig",isPublic:!0,isTrackable:!0},{key:"hasAds",isPublic:!1,isTrackable:!0},{key:"hasReachedPlaybackLimits",isPublic:!1,isTrackable:!0},{key:"hasSsai",isPublic:!1,isTrackable:!0},{key:"pip",isPublic:!0,isTrackable:!0},{key:"recommendationsOptimisation",isPublic:!0,
isTrackable:!0},{key:"watermarkImageType",isPublic:!0,isTrackable:!0},{key:"watermarkImageUrl",isPublic:!0,isTrackable:!1},{key:"watermarkLinkType",isPublic:!0,isTrackable:!0},{key:"watermarkLinkUrl",isPublic:!0,isTrackable:!1}],ia=a=>{var b;return null===(b=B.playerGatekeepers)||void 0===b?void 0:b.includes(a)},L=()=>{var a,b;return(null===(a=window.dailymotion)||void 0===a?0:null===(b=a._do_not_use_4f50ec0e826af64af3b9)||void 0===b?0:b.isGeo2)||ia("PV5_USE_GEO2_IFRAME")||ia("PV5_USE_GEO2_IFRAME_APAC")?
!0:!1},V=(a,b)=>{const c={};ha.filter(d=>d[b]).forEach(d=>{({key:d}=d);c[d]=a[d]});return c},Ha=function(a){let b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{};b&&"object"===typeof b&&Object.keys(b).forEach(c=>{ha.map(d=>{({key:d}=d);return d}).includes(c)&&A()&&(a[c]=b[c],a.hasOverride=!0)});return a},ja=a=>"string"===typeof a?Ia(a):a,Ia=a=>{const b={};a.split("&").forEach(c=>{const [d,f]=c.split("=");d&&f&&(c=d.match(/([a-zA-Z0-9]+)\[([a-zA-Z0-9]+)\]/),"true"===f?b[d]=!0:"false"===f?
b[d]=!1:f.match(/^[0-9]+$/)?b[d]=d.match(/color$/i)?f:parseInt(f):c?b[c[1]]={...b[c[1]],[c[2]]:decodeURIComponent(f)}:b[d]=decodeURIComponent(f))});return b},A=()=>(window.location.hostname||window.origin).endsWith(".dailymotion.com"),ka=(a,b,c,d)=>{a.addEventListener(b,c,d);return()=>{a.removeEventListener(b,c,d)}},N=function(a,b){document.cookie=[`${a}=${b}`,"path=/",`max-age=${2<arguments.length&&void 0!==arguments[2]?arguments[2]:31536E6}`,"samesite=lax;secure"].join(";")},O=a=>{const b=window.document.cookie.split(";").map(c=>
c.trim()).find(c=>c.startsWith(a));return(null===b||void 0===b?void 0:b.split("=")[1])||""},P=()=>{const a=[],b=new window.Uint16Array(32);window.crypto.getRandomValues(b);b.forEach(c=>a.push(`000${c.toString(16)}`.slice(-4)));return`${a[0]}${a[1]}-${a[2]}-${a[3]}-${a[4]}-${a[5]}${a[6]}${a[7]}`};var C=da();let Ea=C.split(",").includes("pes")||"1"===C,g={log:function(a){for(var b=arguments.length,c=Array(1<b?b-1:0),d=1;d<b;d++)c[d-1]=arguments[d];return ea(a,"log",...c)},error:function(a){for(var b=
arguments.length,c=Array(1<b?b-1:0),d=1;d<b;d++)c[d-1]=arguments[d];return ea(a,"error",...c)}},Fa={api:"API",config:"Configuration",contextualembed:"Contextual Embed",cookies:"Cookies",eventbus:"Event Bus",heavyads:"Heavy Ads",init:"Initialization",liveramp:"Liveramp",pip:"Picture In Picture",scaling:"Scaling & aspect ratio",viewability:"Viewability",watchtower:"Watchtower"},t={PUBLIC:{AD_CLICK:"ad_click",AD_COMPANIONSREADY:"ad_companions",AD_DURATIONCHANGE:"ad_durationchange",AD_END:"ad_end",AD_ERROR:"ad_error",
AD_IMPRESSION:"ad_impression",AD_LOADED:"ad_loaded",AD_PAUSE:"ad_pause",AD_PLAY:"ad_play",AD_READYTOFETCH:"ad_readytofetch",AD_START:"ad_start",AD_TIMECHANGE:"ad_timeupdate",PLAYER_ASPECTRATIOCHANGE:"pes_aspectratiochange",PLAYER_CRITICALPATHREADY:"playback_ready",PLAYER_END:"end",PLAYER_ERROR:"error",PLAYER_HEAVYADSINTERVENTION:"player_heavyadsintervention",PLAYER_PIPEXPANDEDCHANGE:"pes_pipexpandedchange",PLAYER_PLAYBACKPERMISSION:"playback_resolution",PLAYER_PLAYBACKSPEEDCHANGE:"playbackspeedchange",
PLAYER_PRESENTATIONMODECHANGE:"pes_presentationmodechange",PLAYER_RECODISPLAY:"recodisplay",PLAYER_SCALEMODECHANGE:"pes_scalemodechange",PLAYER_START:"start",PLAYER_VIDEOCHANGE:"videochange",PLAYER_VIDEOLISTCHANGE:"videolistchange",PLAYER_VIEWABILITYCHANGE:"pes_viewabilitychange",PLAYER_VOLUMECHANGE:"volumechange",VIDEO_BUFFERING:"waiting",VIDEO_DURATIONCHANGE:"video_durationchange",VIDEO_END:"video_end",VIDEO_PAUSE:"pause",VIDEO_PLAY:"play",VIDEO_PLAYING:"playing",VIDEO_PROGRESS:"progress",VIDEO_QUALITIESREADY:"qualitiesavailable",
VIDEO_QUALITYCHANGE:"qualitychange",VIDEO_SEEKEND:"seeked",VIDEO_SEEKSTART:"seeking",VIDEO_START:"video_start",VIDEO_SUBTITLESCHANGE:"subtitlechange",VIDEO_SUBTITLESREADY:"subtitlesavailable",VIDEO_TIMECHANGE:"timeupdate"},PRIVATE:{ALL:"all",BACK_TO_INLINE_DISPLAY_REQUESTED:"pes_pip_back_to_inline_display_requested",CLOSE_PIP_REQUESTED:"pes_pip_close_requested",COLLAPSE_PIP_REQUESTED:"pes_pip_collapse_requested",DISPLAY_POSTER_SOONER:"poster_sooner",EXPAND_PIP_REQUESTED:"pes_pip_expand_requested",
PLAYER_APIREADY:"apiready",PLAYER_FULLSCREENCHANGE:"fullscreenchange",PLAYER_NATIVEPIPCHANGE:"presentationmodechange",PLAYER_STATE:"playerstate",WRITE_UID:"pes_write_uid"}},q={CUSTOMCONFIG:"set-ads-config",FULLSCREEN:"fullscreen",INIT_PIP_IFRAME_CHUNK:"initPesPipChunk",LOAD:"load",LOOP:"loop",MUTED:"muted",NOTIFY_EMBEDDER_URL_CHANGED:"notifyEmbedderURLChanged",NOTIFY_PIP_CHANGED:"notifyPesPipChanged",PAUSE:"pause",PLAY:"play",QUALITY:"quality",PLAYER_VISIBILITY:"notifyPesPlayerVisibility",SCALE:"scaleMode",
SEEK:"seek",SPEED:"speed",STATE:"playerstate",SUBTITLES:"subtitle",UPDATE_NEON_TRACKING_DATA:"updateNeonTrackingData",UPDATE_PARAMS:"updatePesParams",VIEWPORT_RESIZE:"notifyPesViewportSizeChanged",VOLUME:"volume",CONTROLS:"controls",CUSTOM_RECOMMENDATIONS:"customRecommendations"},W=a=>Object.values(t.PUBLIC).includes(a),r=function(a,b){for(var c,d,f=arguments.length,k=Array(2<f?f-2:0),h=2;h<f;h++)k[h-2]=arguments[h];null===(c=a._do_not_use_4f50ec0e826af64af3b9.iframe)||void 0===c?void 0:null===(d=
c.contentWindow)||void 0===d?void 0:d.postMessage(JSON.stringify({command:b,parameters:k}),L()?"https://geo2.dailymotion.com":"https://geo.dailymotion.com");g.log("api",`Sent "${b}" to player iframe`,k)},M=(a,b)=>{window.postMessage(JSON.stringify({event:a,...b}),window.origin)},D=(a,b,c)=>la(a,b,c),ma=(a,b)=>la(null,a,b),la=(a,b,c)=>ka(window,"message",d=>{let {origin:f,data:k}=d;if((f===window.origin||f===(L()?"https://geo2.dailymotion.com":"https://geo.dailymotion.com"))&&k&&"string"===typeof k)try{const h=
JSON.parse(k);"all"!==b&&b!==h.event||null!==a&&a._do_not_use_4f50ec0e826af64af3b9.id!==h.id||(g.log("api","Received event from iframe",h),c(h))}catch(h){}}),Ka=async()=>{var a=await Ja(),b;a:{var c=["h1","h2","h3","title"];for(const d of c)if(c=null===(b=document.querySelector(d))||void 0===b?void 0:b.textContent.trim(),"string"===typeof c&&0<c.length){b=c.substring(0,2E3);break a}b=""}a={content:a,title:b,url:window.location.href};g.log("contextualembed","Extracted data",a);return a},Ja=async()=>
{await new Promise(b=>setTimeout(b,10));let a=document.querySelector("body").innerText;a=a.replace(/\n/g," ");return a.substring(0,8E3)},I=!1,Q=!1,na=new RegExp(/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}/),X=null,La=()=>{const a=O("uid_dm");return null===a||void 0===a?void 0:a.match(na)},Ma=()=>{var a;!1!==(null===(a=B.player)||void 0===a?void 0:a.hasAds)&&(a=O("uid_dm"),X=(null===a||void 0===a?0:a.match(na))?a:P(),g.log("cookies","Initialized UID"))},Na=new RegExp(/^[a-zA-Z0-9-]+$/),
J=null,Oa=()=>{const a=Q,b=O("v1st_dm");a?(g.log("cookies","Got v1st from backend, 3rd party cookie allowed"),J=B.v1st):(null===b||void 0===b?0:b.match(Na))?(g.log("cookies",'Got v1st from 1st party cookie "v1st_dm"'),J=b):(g.log("cookies",'Got v1st from backend, v1st_dm created because 3rd party cookie not allowed and 1st party cookie "v1st_dm" does not exist'),J=B.v1st,I&&N("v1st_dm",J,33696E3))},Pa="xbzwps xbzwyj xkb83k x5xhrd x2k4l07 xgphb5 x2k4kr6 x2k4l64 x1fv3qc x1uzrwn".split(" "),oa={inherit:"",
"16:9":"56.25%","4:3":"75%","1:1":"100%","3:4":"133.3%","9:16":"177.7%"},pa={SMALL:480,MEDIUM:1800,LARGE:2160},Qa="fit fill fillLeft fillRight fillTop fillBottom".split(" "),Y=function(a,b){let c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{};const d=Object.prototype.hasOwnProperty.call(oa,b)?b:"16:9",{id:f,iframe:k,rootNode:h,stateFromPES:p}=a._do_not_use_4f50ec0e826af64af3b9;Object.assign(h.style,{background:"#0d0d0d",height:"inherit"===d?"100%":"",paddingBottom:oa[d],position:"relative",
width:"inherit"===d?"100%":""});Object.assign(k,{height:"100%",width:"100%"});p.playerAspectRatio=d;c.withPesEvent&&M(t.PUBLIC.PLAYER_ASPECTRATIOCHANGE,{id:f,aspectRatio:d});g.log("scaling","Changed aspect ratio",d)},Z=function(a,b){let c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{};const d=Qa.includes(b)?b:"fit",{id:f,stateFromPES:k}=a._do_not_use_4f50ec0e826af64af3b9;k.playerScaleMode=d;c.withPesEvent&&M(t.PUBLIC.PLAYER_SCALEMODECHANGE,{id:f,scaleMode:d});g.log("scaling","Changed scale mode",
d)},qa=()=>{const a=window.navigator.connection;return a&&a.effectiveType?a.effectiveType:null},R=a=>{const b={};Object.keys(a).forEach(function(c){const d=a[c];if(void 0!==d&&null!==d&&""!==d){if(null===d)var f=!1;else"object"!==typeof d?f=!1:(f=Object.getPrototypeOf(d),f=f===Object.prototype||null===f);b[c]=f?R(d):d}});return b},Ra=()=>{const a=window.performance.getEntriesByType("resource").find(c=>c.name===document.currentScript.src),b=function(c){let d=1<arguments.length&&void 0!==arguments[1]?
arguments[1]:6E3;return"number"!==typeof c||Number.isNaN(c)||0>c?null:c>d?d:Math.round(c)};return a?{pes_res:{start_time:b(a.startTime,3E4)},pes_custom:{script_request:b(a.requestStart-a.startTime),script_response_start:b(a.responseStart-a.startTime),script_response_end:b(a.responseEnd-a.startTime)}}:null},{udger:{browserOsFamily:ra,browserOsName:sa,browserUaFamily:ta,browserUaName:ua,browserUaVersion:Sa,deviceType:va},geoip:{visitorAsNumber:wa,visitorCity:Ta,visitorContinent:xa,visitorCountry:ya,
visitorRegion:za},player:K,playerEnv:Ua,trafficSegment:aa}=B,Va=a=>{a={channel:"player",edward:"1.1",sent_ts:Date.now(),events:a.map(R),stack_ctx:{player_stack:"noworker"}};Aa("advertising.heavyAdsIntervention",a)},Aa=async(a,b)=>{try{const c=await window.fetch("https://pebed.dm-event.net",{method:"POST",body:JSON.stringify(b)});200===c.status?g.log("eventbus",`${a} sent`,b):g.error("eventbus",`${a} failed`,c.status,b)}catch(c){g.error("eventbus",`${a} failed`,c.message,b)}},Ba=async a=>{let {name:b,
emptyPlayer:c,pesUUID:d,pesIframeIndex:f,pesIntegrationType:k}=a;a=Date.now();var {pesLastEventTs:h}=window.dailymotion._do_not_use_4f50ec0e826af64af3b9;h={name:b,version:"1.0",data:{browser:{effective_connection_type:qa(),os_family:ra,os_name:sa,ua_family:ta,ua_name:ua,user_agent:window.navigator.userAgent},created_ts:a,device:{type:va,height:window.screen.height,width:window.screen.width},player:{embedder:document.location.href,embedder_hostname:document.location.hostname,pes_uuid:d,pes_iframe_index:f,
pes_integration_type:k,is_empty:c,pubtool:"pes",version:"v-0.0.3663-rc1",settings:V(K,"isTrackable")},timestamp:{created_event:a,delta_previous_event:h?a-h:0},visitor:{as_number:wa,city:Ta,continent:xa,country:ya,id:J,onsite:A(),referer:document.referer,region:za,timezone_offset:-6E4*(new Date).getTimezoneOffset(),traffic_segment:aa}}};K.ownerId&&(h.data.publisher={xid:K.ownerId});window.dailymotion._do_not_use_4f50ec0e826af64af3b9.pesLastEventTs=a;a={channel:"player",edward:"1.1",events:[R(h)],sent_ts:Date.now()};
try{const p=await window.fetch("https://pebed.dm-event.net",{method:"POST",body:JSON.stringify(a),headers:{"content-type":"text/plain; charset=UTF-8"}});200===p.status?g.log("watchtower",b,"sent",a.events[0]):g.error("watchtower",b,"failed",p.status,a.events[0])}catch(p){g.error("watchtower",b,"failed",p.message,a.events[0])}},Wa={initialize:a=>{const {id:b,observer:c,rootNode:d,settings:f,stateFromPES:k}=a._do_not_use_4f50ec0e826af64af3b9,h={};a._do_not_use_4f50ec0e826af64af3b9.removeAllListeners=
D(a,t.PRIVATE.ALL,e=>{let {id:m,event:l,fullscreen:n,mode:u,playerHeavyAdsInterventionReports:v,playerHeavyAdsEvents:G}=e;[t.PRIVATE.PLAYER_FULLSCREENCHANGE,t.PRIVATE.PLAYER_NATIVEPIPCHANGE].includes(l)&&(e=l===t.PRIVATE.PLAYER_FULLSCREENCHANGE?n?"fullscreen":"inline":"inline"===u?"inline":"nativePip",k.playerPresentationMode=e,M(t.PUBLIC.PLAYER_PRESENTATIONMODECHANGE,{id:m,playerPresentationMode:e}));h[l]&&W(l)&&(l===t.PUBLIC.PLAYER_HEAVYADSINTERVENTION?(h[l].forEach(w=>{({cb:w}=w);w({playerHeavyAdsInterventionReports:v})}),
g.log("heavyads","Received reports",v),0<G.length&&(g.log("heavyads","Received events",G),Va(G))):a.getState().then(w=>{h[l].slice().forEach(y=>{({cb:y}=y);y(w)})}))});const p=e=>{const m=D(a,t.PRIVATE.PLAYER_STATE,l=>{Object.assign(l,k);e(l)});r(a,q.STATE);return m};a.pause=()=>{g.log("api","Called player.pause()");r(a,q.PAUSE)};a.play=()=>{g.log("api","Called player.play()");r(a,q.PLAY)};a.seek=e=>{g.log("api","Called player.seek()",e);r(a,q.SEEK,e)};a.setCustomRecommendations=e=>{g.log("api","Called player.setCustomRecommendations()",
e);if(f.enableCustomRecommendations)return e=e.filter(m=>"string"===typeof m&&m.match(/^x[a-zA-Z0-9-_]+$/)),30<e.length&&(console.warn("Custom recommendations are restricted to 30 videos, excess videos will be ignored"),e=e.slice(0,30)),r(a,q.CUSTOM_RECOMMENDATIONS,e);console.warn("Custom recommendations are disabled for that player")};a.setMute=e=>{g.log("api","Called player.setMute()",e);r(a,q.MUTED,e)};a.setQuality=e=>{g.log("api","Called player.setQuality()",e);r(a,q.QUALITY,e)};a.setSubtitles=
e=>{g.log("api","Called player.setSubtitles()",e);r(a,q.SUBTITLES,e)};a.setVolume=e=>{g.log("api","Called player.setVolume()",e);r(a,q.VOLUME,e)};a.setFullscreen=e=>{g.log("api","Called player.setFullscreen()",e);r(a,q.FULLSCREEN,e)};a.setControls=()=>{console.warn("The setControls method has been deprecated. Please check https://developers.dailymotion.com/player/#changelog for more details")};a.setCustomConfig=e=>{g.log("api","Called player.setCustomConfig()",e);r(a,q.CUSTOMCONFIG,e)};a.setLoop=
e=>{g.log("api","Called player.setLoop()",e);r(a,q.LOOP,e)};a.setPlaybackSpeed=e=>{g.log("api","Called player.setPlaybackSpeed()",e);r(a,q.SPEED,e)};a.setAspectRatio=e=>{g.log("api","Called player.setAspectRatio()",e);Y(a,e,{withPesEvent:!0})};a.setScaleMode=e=>{g.log("api","Called player.setScaleMode()",e);r(a,q.SCALE,e);Z(a,e,{withPesEvent:!0})};a.loadContent=e=>{let {video:m,playlist:l,startTime:n}=e;g.log("API","Called player.loadContent()",{video:m,playlist:l,startTime:n});e="on"===f.autostart||
"firstTimeViewable"===f.autostart&&c.wasViewableAtLeastOnce;if(A()){const u=window.location.href;g.log("API","sendCommandToPlayer(COMMANDS.NOTIFY_EMBEDDER_URL_CHANGED), with url:",u);r(a,q.NOTIFY_EMBEDDER_URL_CHANGED,u)}r(a,q.LOAD,m,{playlist:l,start:n,autoplay:e})};a.updateParams=e=>{g.log("api","Called player.updateParams()",e);void 0!==e.enableControls&&console.warn("The enableControls parameter from updateParams method has been deprecated. Please check https://developers.dailymotion.com/player/#changelog for more details");
void 0!==e.aspectRatio&&Y(a,e.aspectRatio,{withPesEvent:!0});void 0!==e.scaleMode&&Z(a,e.scaleMode,{withPesEvent:!0});r(a,q.UPDATE_PARAMS,e)};a.on=function(e,m){let {once:l=!1}=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{};g.log("api","Called player.on()",e);if(void 0!==e)if("string"===typeof e&&W(e))if("function"!==typeof m)console.warn(`The specified callback should be a function, received ${m}`);else if(h[e]||(h[e]=[]),h[e].find(v=>{({originalCb:v}=v);return v===m}))console.warn(`Callback duplication detected for ${e}`);
else{var n=m;l&&(m=function(){u();n(...arguments)});var u=()=>{h[e]&&(h[e]=h[e].filter(v=>v.originalCb!==n))};h[e].push({originalCb:n,cb:m});return u}else console.warn(`Unknown event, received ${e}`)};a.off=(e,m)=>{g.log("api","Called player.off()",e);void 0!==e&&("string"===typeof e&&W(e)?h[e]?void 0===m?delete h[e]:"function"!==typeof m?console.warn(`The specified callback should be a function, received ${m}`):h[e]=h[e].filter(l=>l.originalCb!==m):console.warn(`No listener on ${e} to remove`):console.warn(`Unknown event, received ${e}`))};
a.getState=()=>{g.log("api","Called player.getState()");return new Promise((e,m)=>{const l=D(a,t.PUBLIC.PLAYER_HEAVYADSINTERVENTION,()=>{n();l();m();console.warn(`player.getState() rejected : player ${b} has been destroyed by Heavy Ads`)}),n=p(u=>{n();l();e(u)})})};a.getRootNode=()=>{g.log("api","Called player.getRootNode()");return d};a.getSettings=()=>{g.log("api","Called player.getSettings()");return V(f,"isPublic")};A()&&(a.setControlsForNeon=e=>{r(a,q.CONTROLS,e)})}},ba=!1;class Xa{constructor(a){let {embedIndex:b,
emptyPlayer:c,iframe:d,iframeId:f,observer:k,placeholderNode:h,rootNode:p,settings:e,spinner:m}=a;a=window.innerWidth<=pa.SMALL?"smallViewport":"largeViewport";let l="off"===e.pip?"disabled":"enabled";this.hasReceivedVideoChange=this.isEmpty=this.apiReadyReceived=!1;this._do_not_use_4f50ec0e826af64af3b9={id:f,iframe:d,index:b,initialized:!1,observer:k,placeholderNode:h,rootNode:p,settings:e,spinner:m,stateFromPES:{playerAspectRatio:null,playerIsViewable:null,playerPip:null,playerPipDisplay:a,playerPipIsExpanded:!1,
playerPipStatus:l,playerPresentationMode:"inline",playerScaleMode:null},viewportResizeListener:null};k.init(d);this.isEmpty=c;Y(this,e.aspectRatio);Z(this,e.scaleMode);if(!La()){let u=D(this,t.PRIVATE.WRITE_UID,()=>{var v;!1!==(null===(v=B.player)||void 0===v?void 0:v.hasAds)&&(I&&N("uid_dm",X,33696E3),g.log("cookies","Wrote UID"));u()})}this.apiReadyReceived=new Promise(u=>{let v=D(this,t.PRIVATE.PLAYER_APIREADY,()=>{d.removeAttribute("name");m&&(d.style.opacity=1,m.remove());v();u()})});let n=D(this,
t.PRIVATE.DISPLAY_POSTER_SOONER,()=>{d.style.opacity=1;m.remove();n()});Wa.initialize(this);"off"===e.pip?ba=Promise.resolve():(window.dailymotion._do_not_use_4f50ec0e826af64af3b9.playerSelectedForPip?console.warn(`[${e.id}] ${"PIP is already enabled with another configuration"}`):window.dailymotion._do_not_use_4f50ec0e826af64af3b9.playerSelectedForPip=this,ba=window._dmDynamicImportPolyfill("pes.pip.bbcf893e.js"))}initialize(){let {initialized:a}=this._do_not_use_4f50ec0e826af64af3b9;if(a)return a;
let {settings:{autostart:b,pip:c},id:d,iframe:f,observer:k,rootNode:h}=this._do_not_use_4f50ec0e826af64af3b9;k.earlyObserve(h);a=(async()=>{await Promise.all([ba,this.apiReadyReceived]);k.unobserve(h);D(this,t.PUBLIC.PLAYER_VIDEOCHANGE,p=>{({title:p}=p);f.setAttribute("title",`Dailymotion video player - ${p.replace(/&/g,"&amp;").replace(/"/g,"&quot;")}`);this.isEmpty&&!this.hasReceivedVideoChange&&(k.unobserve(h),k.observe(h));this.hasReceivedVideoChange=!0});"off"!==c&&(window.dailymotion._do_not_use_4f50ec0e826af64af3b9.playerSelectedForPip===
this&&window.dailymotion.pipResume(),r(this,q.INIT_PIP_IFRAME_CHUNK));Ya();"firstTimeViewable"===b&&Za(this);$a(this);g.log("init",`Player ${d} fully initialized`);k.observe(h);return this})();return this._do_not_use_4f50ec0e826af64af3b9.initialized=a}destroy(){let {id:a,observer:b,placeholderNode:c,removeAllListeners:d,rootNode:f,viewportResizeListener:k}=this._do_not_use_4f50ec0e826af64af3b9;g.log("api","Called player.destroy()");b.unobserve(f);d();ab(this);f.parentNode.replaceChild(c,f);this===
window.dailymotion._do_not_use_4f50ec0e826af64af3b9.playerSelectedForPip&&(window.dailymotion.pipClose(),window.dailymotion._do_not_use_4f50ec0e826af64af3b9.playerSelectedForPip=null);window.removeEventListener("resize",k);delete window.dailymotion._do_not_use_4f50ec0e826af64af3b9.players[a]}isEligibleForPipDisplay(a){let {settings:{pip:b}}=this._do_not_use_4f50ec0e826af64af3b9;return"off"===b?{status:!1,reason:"PIP is OFF"}:this.isEmpty&&!this.hasReceivedVideoChange?{status:!1,reason:"empty embed without videochange event"}:
a?{status:!0,reason:"PIP is ON and was viewable at least once"}:{status:"instant"===b,reason:"instant"===b?"PIP is INSTANT":"was not viewable at least once"}}}let Za=a=>{const b=D(a,t.PUBLIC.PLAYER_VIEWABILITYCHANGE,c=>{let {viewable:d,wasViewableAtLeastOnce:f}=c;a&&(d||a.isEligibleForPipDisplay(f).status)&&(b(),a.play())})},$a=a=>{a._do_not_use_4f50ec0e826af64af3b9.viewportResizeListener=()=>{r(a,q.VIEWPORT_RESIZE,{width:window.innerWidth,height:window.innerHeight})};window.addEventListener("resize",
a._do_not_use_4f50ec0e826af64af3b9.viewportResizeListener)},Ya=()=>{ma(t.PUBLIC.PLAYER_VIEWABILITYCHANGE,a=>{let {viewable:b,id:c}=a;if(a=window.dailymotion._do_not_use_4f50ec0e826af64af3b9.players[c])a._do_not_use_4f50ec0e826af64af3b9.stateFromPES.playerIsViewable=b,r(a,q.PLAYER_VISIBILITY,b)})},ab=a=>{const b=c=>{console.warn(`Invalid call to player.${c}() : player ${a._do_not_use_4f50ec0e826af64af3b9.id} has been destroyed`)};Object.keys(a).forEach(c=>{"function"===typeof a[c]&&(a[c]=()=>{b(c)})});
Object.getOwnPropertyNames(Object.getPrototypeOf(a)).forEach(c=>{"constructor"!==c&&"function"===typeof a[c]&&(a[c]=()=>{b(c)})})},Ca=[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1],cb=(a,b,c,d)=>{if(!0===b)return g.log("viewability","No header overlapping ! Reason: IO isVisible is true"),{status:!1,marginTop:null};const {x:f,y:k,width:h,height:p}=a.getBoundingClientRect();if(0<=k)return g.log("viewability",`Overlapping detection canceled ! Reason : Player is not about to pass above the fold, y:${k}`),{status:!1,
marginTop:null};a=document.elementFromPoint(f+Math.round(.5*h),k+Math.round(p*(1-d)));if(!a)return g.log("viewability","No header overlapping ! Reason: No overlapping element"),{status:!1,marginTop:null};if(c.isSameNode(a))return g.log("viewability","No header overlapping ! Reason: Overlapping element is the same as the player iframe"),{status:!1,marginTop:null};c=bb(a);if(!c)return g.log("viewability",'No header overlapping ! Reason: Overlapping element or ancestors are not in "fixed" position'),
{status:!1,marginTop:null};const {x:e,y:m,width:l,height:n}=c.getBoundingClientRect();g.log("viewability",`Overlapping header detection data :
        - IO isVisible : ${b}
        - targetX : ${f}
        - targetY : ${k}
        - targetWidth : ${h}
        - targetHeight : ${p}
        - fixedElementX : ${e}
        - fixedElementY: ${m}
        - fixedElementWidth: ${l}
        - fixedElementHeight: ${n}
        - fixed element:`,c,"\n        - overlapping element:",a);if(0!==m)return g.log("viewability","No header overlapping ! Reason: Overlapping element Y position is not 0"),{status:!1,marginTop:null};if(!(e<=f&&l>=h))return g.log("viewability","No header overlapping ! Reason: Overlapping element is not fully covering the player width"),{status:!1,marginTop:null};g.log("viewability","Fixed header is overlapping player iframe");return{status:!0,marginTop:n}},bb=a=>{try{for(;a;){const b=window.getComputedStyle(a).getPropertyValue("position").toLowerCase();
if("fixed"===b||"sticky"===b)return a;a=a.parentNode instanceof HTMLElement&&"BODY"!==a.tagName?a.parentNode:null}return null}catch(b){return null}};class db{constructor(){this.uiActionOrigin=this.intersectionObserver=null;this.earlyObserverMode=this.wasViewableAtLeastOnce=!1;this.playerIframe=null;this.hasCompletedHeaderDetection=!1;this.intersectionObserver=new window.IntersectionObserver(this.intersectionObserverCallback.bind(this),{threshold:Ca})}init(a){this.playerIframe=a;g.log("viewability",
"Observer initialized with header detection")}intersectionObserverCallback(a){a.forEach(b=>{let {intersectionRatio:c,target:d,isVisible:f}=b;if((b=.5<=c)&&!this.hasCompletedHeaderDetection&&0>=d.getBoundingClientRect().y){let {status:k,marginTop:h}=cb(d,f,this.playerIframe,.5);k&&(this.hasCompletedHeaderDetection=!0,b=!1,this.intersectionObserver.disconnect(),this.intersectionObserver=null,g.log("viewability","Defining new observer with root marginTop",h),this.intersectionObserver=new window.IntersectionObserver(this.intersectionObserverCallback.bind(this),
{rootMargin:`-${h}px 0px 0px 0px`,threshold:Ca}),this.intersectionObserver.observe(d))}b&&!this.wasViewableAtLeastOnce&&(g.log("viewability","Player iframe was viewable at least once"),this.wasViewableAtLeastOnce=!0);this.earlyObserverMode||M(t.PUBLIC.PLAYER_VIEWABILITYCHANGE,{id:d.id,viewable:b,wasViewableAtLeastOnce:this.wasViewableAtLeastOnce,...(this.uiActionOrigin?{uiActionOrigin:this.uiActionOrigin}:{})});this.uiActionOrigin=null})}observe(a){var b;null===(b=this.intersectionObserver)||void 0===
b?void 0:b.observe(a)}earlyObserve(a){var b;g.log("viewability","Early intersection observer has started");this.earlyObserverMode=!0;null===(b=this.intersectionObserver)||void 0===b?void 0:b.observe(a)}unobserve(a){var b;this.earlyObserverMode=!1;null===(b=this.intersectionObserver)||void 0===b?void 0:b.unobserve(a)}disconnect(){var a;null===(a=this.intersectionObserver)||void 0===a?void 0:a.disconnect()}setUIActionOrigin(a){this.uiActionOrigin=a}}let Da={create:async function(a,b,c,d){var f;let {videoId:k,
playlistId:h,playerId:p,params:e,settings:m,referrerPolicy:l}=4<arguments.length&&void 0!==arguments[4]?arguments[4]:{};if("embed"!==d||null!==(f=document.body)&&void 0!==f&&f.contains(a)){var n=a.id||`dailymotion-instance-${P()}`,u=a.parentNode;f=window.dailymotion._do_not_use_4f50ec0e826af64af3b9.iframeIndex++;var v=!k&&!h,G=new db,w=ja(e),y=ja(m),ca=`pes${(null===w||void 0===w?0:w.dmPubtool)?`-${w.dmPubtool}`:""}`,z=window.dailymotion._do_not_use_4f50ec0e826af64af3b9.settings,x=z[p];if(void 0===
x)try{x=await (await window.fetch(`${L()?"https://geo2.dailymotion.com":"https://geo.dailymotion.com"}/player/${p}.json`,{method:"GET"})).json(),g.log("api","Fetched player settings",x),"server_error"===x.status&&console.warn(`${"An unexpected error occured when retrieving player configuration"} : ${x.id}`),"not_found"===x.status&&console.warn(`${"The player configuration ID has not been found"} : ${x.id}`),"deleted"===x.status&&console.warn(`${"The player configuration ID has been deleted"} : ${x.id}`),
z[x.id]=x}catch(S){console.error("Settings fetch error: ",S);return}x=Ha(x,y);w=eb(k,h,p,w,l);z=document.createElement("div");z.id=n;z.classList.add("dailymotion-player-root");z.classList.add(`dailymotion-player-${p}`);y=document.createElement("div");y.className="dailymotion-player-wrapper";Object.assign(y.style,{height:"100%",overflow:"hidden",position:"absolute",width:"100%",margin:"0.00001px"});var E,H=document.createElement("div"),F=640<((null===u||void 0===u?void 0:null===(E=u.getBoundingClientRect())||
void 0===E?void 0:E.width)||0)?"48":"40";Object.assign(H.style,{height:`${F}px`,left:"50%",position:"absolute",top:"50%",transform:"translate3d(-50%, -50%, 0)",width:`${F}px`});H.innerHTML=`<svg
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      height="${F}"
      viewBox="0 0 50 50"
      width="${F}"
    >
      <circle
        cx="25"
        cy="25"
        fill="none"
        r="20"
        stroke="#fff"
        stroke-dasharray="125.6, 125.6"
        stroke-width="4"
        transform="rotate(-90 25 25)"
      />
    </svg>`;H.querySelector("circle").animate([{strokeDashoffset:"125.6"},{strokeDashoffset:"0"},{strokeDashoffset:"-125.6"}],{duration:1200,iterations:Infinity});E=new Xa({embedIndex:b,emptyPlayer:v,iframe:w,iframeId:n,observer:G,placeholderNode:a,rootNode:z,settings:x,spinner:H});window.dailymotion._do_not_use_4f50ec0e826af64af3b9.players[n]=E;y.appendChild(H);z.appendChild(y);u.replaceChild(z,a);n=await fb({embedIndex:b,iframeId:n,pesIframeIndex:f,pesIntegrationType:d,pesUUID:c,pubtool:ca,settings:x});
w.name=encodeURIComponent(n);y.appendChild(w);g.log("init","Injected iframe in the DOM");Ba({name:"vital_pes_iframe_start",emptyPlayer:v,pesIframeIndex:f,pesIntegrationType:d,pesUUID:c});return E}console.warn("The Player Embed Script can't be injected in document head, please use Library Script instead. More details: https://developers.dailymotion.com/guides/getting-started-with-web-sdk/#player-library-script")}},eb=function(a,b,c){let d=3<arguments.length&&void 0!==arguments[3]?arguments[3]:{},f=
4<arguments.length?arguments[4]:void 0;const k=document.createElement("iframe"),h="default"!==c?`/player/${c}.html`:"/player.html",p={...(a&&{video:a}),...(b&&{playlist:b})};Object.keys(d).filter(l=>!p[l]).forEach(l=>{d[l]&&"object"===typeof d[l]?Object.keys(d[l]).forEach(n=>{p[`${l}[${n}]`]=encodeURIComponent(d[l][n])}):p[l]=encodeURIComponent(d[l])});var e=window.location.href.match(/dmDevBackendEnv=[-_a-zA-Z0-9]+/);null!==e&&([,e]=e[0].split("="),p.dmDevBackendEnv=e);e=Object.keys(p).map(l=>`${l}=${p[l]}`).join("&");
const m=["autoplay","fullscreen","picture-in-picture",...(window.navigator.canShare?["web-share"]:[])];Object.assign(k,{allow:m.join("; "),className:"dailymotion-player",frameBorder:0,src:`${L()?"https://geo2.dailymotion.com":"https://geo.dailymotion.com"}${h}?${e}`,title:"Dailymotion video player",...(f&&{referrerPolicy:f})});k.style.opacity=0;return k},fb=async a=>{let {embedIndex:b,iframeId:c,pesIframeIndex:d,pesIntegrationType:f,pesUUID:k,pubtool:h,settings:p}=a;const {trafficSegment:e,playerGatekeepers:m,
player:l}=B,{location:n,origin:u,innerWidth:v,innerHeight:G}=window,{hasOverride:w,enableReceiveUrlLocation:y,enableSharingUrlLocation:ca,enableContextualContent:z}=p,{pesLastEventTs:x,neonTrackingData:E}=window.dailymotion._do_not_use_4f50ec0e826af64af3b9;a={width:v,height:G};const H=w?p:void 0;let F=null;if(y||ca)n.hostname?F=n.href:n.ancestorOrigins&&(F=n.ancestorOrigins[0]);let S=null;try{S=(new URL(document.referrer)).origin}catch(T){}const gb=z?await Ka():null,[hb]=await Promise.all([(async()=>
{if(!Pa.includes(null===l||void 0===l?void 0:l.ownerId))return Promise.resolve(null);try{await window._dmDynamicImportPolyfill("pes.liveramp.7919fbb0.js");const T=await window.dailymotion._do_not_use_4f50ec0e826af64af3b9.getLiverampEnvelope();return Promise.resolve(T)}catch(T){return Promise.reject(T)}})(),Ga()]);N("_TEST_","1");I="1"===O("_TEST_");N("_TEST_",null,0);g.log("cookies",`1st party cookies are ${I?"allowed":"blocked"}`);A()?Q=I:"undefined"!==typeof window.dmCookie3rdPartyAllowed&&(Q=window.dmCookie3rdPartyAllowed,
delete window.dmCookie3rdPartyAllowed);Oa();Ma();return JSON.stringify({dmInternalData:{contextualPageData:gb,cookies1stPartyAvailable:I,cookies3rdPartyAvailable:Q,embedder:F,embedIndex:b,forcedSettings:H,gatekeepers:m,iframeId:c,initialViewportSize:a,liverampEnvelope:hb,logger:da(),neonTrackingData:E,pesIframeIndex:d,pesIntegrationType:f,pesLastEventTs:x,pesPlayerVersion:"v-0.0.3663-rc1",pesUUID:k,pubtool:h,referer:S,targetOrigin:u,ts:e,uid:X,v1st:J}})};C=()=>{g.log("api","Called disabled PIP method");
console.warn("PIP is disabled in the configuration")};let ib=a=>{g.log("api","Called dailymotion.forwardNeonTrackingData()",a);const {players:b}=window.dailymotion._do_not_use_4f50ec0e826af64af3b9,c=Object.keys(b);0===c.length?window.dailymotion._do_not_use_4f50ec0e826af64af3b9.neonTrackingData=a:r(b[c[0]],q.UPDATE_NEON_TRACKING_DATA,a)},jb=()=>{const {udger:{browserOsFamily:a,browserOsName:b,browserUaFamily:c,browserUaName:d,browserUaVersion:f}={}}=B;return{osFamily:a,osName:b,uaFamily:c,uaName:d,
uaVersion:f}},kb={createPlayer:async function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{};g.log("api","Called dailymotion.createPlayer()",a,b);const {settings:c,embedScriptIndex:d,pesUUID:f}=window.dailymotion._do_not_use_4f50ec0e826af64af3b9,k=document.querySelector(`#${a}`);if(!k)return Promise.reject(Error(`${"DOM element ID not found"} : #${a}`));if(k.classList.contains("dailymotion-player-wrapper"))return Promise.reject(Error(`${"A player instance is already attached to this DOM element"} : #${a}`));
if(b&&"object"!==typeof b)return Promise.reject(Error("Player options invalid, please use an object"));b.player||(1===Object.keys(c).length?b.player=Object.keys(c)[0]:(1<Object.keys(c).length&&console.warn("Several player configurations are imported, please specify a player configuration ID"),b.player="default"));b=await Da.create(k,d,f,"lib",{videoId:b.video,playlistId:b.playlist,playerId:b.player,params:b.params,settings:b.settings,referrerPolicy:b.referrerPolicy});return null===b||void 0===b?void 0:
b.initialize()},events:t.PUBLIC,getAllPlayers:()=>{g.log("api","Called dailymotion.getAllPlayers()");const {players:a}=window.dailymotion._do_not_use_4f50ec0e826af64af3b9,b=[];if(0===Object.keys(a).length)return Error("No player found in the page");Object.values(a).forEach(c=>b.push(null===c||void 0===c?void 0:c.initialize()));return b},getPlayer:a=>{g.log("api","Called dailymotion.getPlayer()",a);const {players:b}=window.dailymotion._do_not_use_4f50ec0e826af64af3b9,c=b[a];if(0===Object.keys(b).length)return Promise.reject(Error("No player found in the page"));
if(void 0===a){var d;return 1<Object.keys(b).length?Promise.reject(Error("There are multiple players in the page, please specify an ID")):null===(d=Object.values(b)[0])||void 0===d?void 0:d.initialize()}return void 0===c?Promise.reject(Error(`${"Player ID not found"} : #${a}`)):null===c||void 0===c?void 0:c.initialize()},pipClose:C,pipCollapse:C,pipExpand:C,pipRepaint:C,pipResume:C,...(A()&&{forwardNeonTrackingData:ib,getEnvironmentInfo:jb}),_do_not_use_4f50ec0e826af64af3b9:{api:null,embedScriptIndex:1,
iframeIndex:1,neonTrackingData:null,pesUUID:null,players:{},playerSelectedForPip:null,screenId:P(),settings:{}}};window._dmDynamicImportPolyfill=a=>{const b=`pes-${a}`;var c=document.querySelector(`script[id="${b}"]`);if(c)return fa(c);c=document.createElement("script");c.src=`${"https://static1.dmcdn.net/playerv5"}/${a}`;c.id=b;a=fa(c);document.body.appendChild(c);return a};let U=B.player;if(!U)throw Error("Backend settings not set");let {id:lb,status:mb}=U;(async a=>{var b=document.currentScript;
let {dataset:{video:c,playlist:d,params:f,settings:k},referrerPolicy:h,src:p}=b;var e=!c&&!d;let m=p.match(/\/libs\//)?"lib":"embed";g.log("init","Started PES","lib"===m?"(lib)":"(embed script)");let l=!!p.match(/geo2/)||!1,n=P();null!==(a=window.dailymotion)&&void 0!==a&&a.createPlayer||(window.dailymotion={...window.dailymotion,...kb},g.log("init","Injected public API"));Ba({name:"vital_pes_enter",emptyPlayer:"lib"===m?null:e,pesIntegrationType:m,pesUUID:n});window.dailymotion._do_not_use_4f50ec0e826af64af3b9.pesUUID=
n;window.dailymotion._do_not_use_4f50ec0e826af64af3b9.isGeo2=l;g.log("init",`PES UUID: ${n}`);"ok"===mb&&(window.dailymotion._do_not_use_4f50ec0e826af64af3b9.settings[U.id]=U);"function"===typeof window.dailymotion.onScriptLoaded&&(g.log("init","Running dailymotion.onScriptLoaded()"),window.dailymotion.onScriptLoaded(),delete window.dailymotion.onScriptLoaded);"lib"===m?g.log("init","Library script loaded"):(a=window.dailymotion._do_not_use_4f50ec0e826af64af3b9.embedScriptIndex++,g.log("init","Embed script loaded",
`Index ${a}`),e={name:"life_cycle.embedStart",version:"1.0",data:{context:{visitor_group:Math.ceil(aa/1E4)},created_ts:Date.now(),empty_player:e,info:{browser:{effective_connection_type:qa(),os_family:ra,os_name:sa,ua_family:ta,ua_name:ua,ua_version:Sa,user_agent:window.navigator.userAgent},device:{type:va,width:window.innerWidth,height:window.innerHeight},player:{config:V(K,"isTrackable"),embedder:document.location.href,embedder_hostname:document.location.hostname,env:Ua,is_geo:!0,is_geo2:l,secure:!0,
version:"v-0.0.3663-rc1"},visitor:{as_number:wa,continent:xa,country:ya,onsite:A(),referer:document.referer,region:za,timezone_offset:-6E4*(new Date).getTimezoneOffset(),traffic_segment:aa}},perf:Ra(),settings:{embed_index:a,pubtool:"pes"}}},K.ownerId&&(e.data.info.publisher={type:"player",xid:K.ownerId}),e={channel:"player",edward:"1.1",sent_ts:Date.now(),events:[R(e)],stack_ctx:{player_stack:"noworker"}},Aa("life_cycle.embedStart",e),e={videoId:c,playlistId:d,playerId:lb,params:f,settings:k,referrerPolicy:h},
g.log("init","Creating player iframe",e),b=await Da.create(b,a,n,"embed",e),null===b||void 0===b?void 0:b.initialize())})();return{B:pa,C:q,E:300,a:t,b:ka,c:r,d:ma,l:g,s:M}}()
// pv5template